spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:isme;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: root
    password: 123456
  sql:
    init:
      schema-locations: classpath:db/h2.sql
      mode: always